#!/bin/bash

#Monitors changes in the log in the log files stored within the directory. These files keep track of anything and everything that is being done within the system
inotifywait -r /var/log

cd /var/log

#Check up on recently installed and updated packages
tail dpkg.log
